### ISSUE TITLE
User Can Message

### ISSUE THREAD

**Issue by chrisahn1** [chrisahn1/Final-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can enter messages on the chat page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

This Issue is creating the chat page before a home page that has the rooms
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Issue 1 Desktop](https://user-images.githubusercontent.com/22688744/165081356-1cda131b-eee3-4ec8-bde4-cdc85a6c7d13.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a chat page header that has the Title and the Exit Button with space in between
- [x] Create 2 columns where the first column is the messaging and the second column shows info such as Room Name and Users
- [x] The Texting column should be larger than the second column
- [x] On the bottom, have the text input and the send button
- [x] Whenever a user clicks the send button, make sure it's input is required.
- [x] Create a js/reactjs page that sets up the express, app, http, and server that are required.
- [x] Set up the required socket io in script in the script or another js/reactjs file.
- [x] When the user clicks on send button, the message should appear in message column.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
