### ISSUE TITLE
User can click on hiking location and view its details

### ISSUE THREAD

**Issue by chrisahn1** [chrisahn1/Final-Project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

When the user clicks on a hiking trail, it opens to the next page where the hiking trails detailed info is shown.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![3 Location Desktop](https://user-images.githubusercontent.com/22688744/163290325-b8310be9-6d2d-4858-b8b3-61c23237719f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] Have the search results animated and clickable. When clicked, it moves to the hiking trail page.
- [ ] The search bar should be gone
- [ ] The image and star rank should be on the left side of the page while the hiking trail name, address, city, state and zip code should be displayed on the top right side while the comments are on the bottom right side.
- [ ] The image should be retrieved from the Google map api as the default image.
- [ ] For testing dummie account: The Star rank should display stars that are empty.
- [ ] The Star button should ask for rank from 1-5. 
- [ ] When the star rank is entered, it displays the filled stars as yellow or similar color.
- [ ] Have comment section displays comment of all users(try testing with dummie accounts).
- [ ] Each comment displays the username, date posted and the comment
- [ ] Have the comment button below

- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
